//! The multi-chain surface, end to end through the `cwbwallet` binary.
//!
//! Everything here is offline. Key derivation, addresses, signatures and the
//! store are the parts that must be right before a node is ever involved —
//! and they are the parts that silently produce a *plausible* wrong answer
//! when they are not, which is what these tests exist to catch.
//!
//! The expected values come from `testvectors/multichain.json`, generated by
//! each chain's own SDK.

mod common;

use serde_json::Value;

use common::Wallet;

/// The canonical BIP-39 test phrase every vector in the file derives from.
const PHRASE: &str =
    "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about";

const CHAINS: [&str; 5] = ["evm", "solana", "cardano", "midnight", "ecash"];

fn vectors() -> Value {
    let path =
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../testvectors/multichain.json");
    serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap()
}

/// A wallet holding the test phrase on every chain.
fn seeded() -> Wallet {
    let wallet = Wallet::new();
    for chain in CHAINS {
        wallet.json(&[
            "--chain",
            chain,
            "account",
            "import-mnemonic",
            "-m",
            PHRASE,
            "--label",
            chain,
        ]);
    }
    wallet
}

// ==================================================================== derivation

/// The one test that ties the binary to the outside world: every chain must
/// produce the address its own SDK produces from the same phrase.
#[test]
fn every_chain_derives_the_address_its_official_sdk_derives() {
    let wallet = Wallet::new();
    let vectors = vectors();

    let expected = [
        // The address every Ethereum tool produces for this phrase.
        (
            "evm",
            "0x9858EfFD232B4033E47d90003D41EC34EcaEda94".to_string(),
        ),
        (
            "solana",
            vectors["solana"]["accounts"][0]["address"]
                .as_str()
                .unwrap()
                .to_string(),
        ),
        (
            "cardano",
            vectors["cardano"]["accounts"][0]["base_addr_testnet"]
                .as_str()
                .unwrap()
                .to_string(),
        ),
    ];

    for (chain, want) in expected {
        let account = wallet.json(&[
            "--chain",
            chain,
            "account",
            "import-mnemonic",
            "-m",
            PHRASE,
            "--label",
            chain,
        ]);
        assert_eq!(
            account["address"], want,
            "{chain} derived the wrong address"
        );
        assert_eq!(account["chain"], chain);
    }

    // Midnight renders per network, so it is checked through its mainnet form,
    // which is what the SDK reports.
    let midnight = wallet.json(&[
        "--chain",
        "midnight",
        "account",
        "import-mnemonic",
        "-m",
        PHRASE,
        "--label",
        "midnight",
    ]);
    assert!(midnight["address"]
        .as_str()
        .unwrap()
        .starts_with("mn_addr_preview1"));
}

#[test]
fn each_chain_reports_its_own_derivation_path() {
    let wallet = seeded();
    let paths = [
        ("evm", "m/44'/60'/0'/0/0"),
        ("solana", "m/44'/501'/0'/0'"),
        ("cardano", "m/1852'/1815'/0'/0/0"),
        ("midnight", "m/44'/2400'/0'/0/0"),
        ("ecash", "m/44'/1899'/0'/0/0"),
    ];
    for (chain, path) in paths {
        let shown = wallet.json(&["--chain", chain, "account", "show", chain]);
        assert_eq!(shown["derivation_path"], path, "{chain}");
    }
}

/// One phrase, an address on every chain, one command.
#[test]
fn every_chain_can_be_seeded_from_a_single_mnemonic_at_once() {
    let wallet = Wallet::new();
    let created = wallet.json(&["account", "new", "--every-chain", "--label", "me"]);
    let accounts = created.as_array().expect("one entry per chain");
    assert_eq!(accounts.len(), CHAINS.len());

    let chains: Vec<&str> = accounts
        .iter()
        .map(|a| a["chain"].as_str().unwrap())
        .collect();
    assert_eq!(chains, CHAINS);

    // Distinct labels, so nothing collides, and each says what it is.
    for (account, chain) in accounts.iter().zip(CHAINS) {
        assert_eq!(account["label"], format!("me-{chain}"));
    }

    // They all came from the one phrase, so they share a single recall entry.
    let recalled = wallet.json(&["recent", "list"]);
    assert_eq!(recalled.as_array().unwrap().len(), 1);
    assert_eq!(recalled[0]["kind"], "mnemonic");
}

/// The TUI's `New wallet` is this command. It must *create* — landing on a
/// fresh index and making nothing is the bug this pins.
#[test]
fn making_a_wallet_derives_every_chain_at_one_index() {
    let wallet = Wallet::new();

    for expected_index in 0..3u32 {
        let created = wallet.json(&[
            "account",
            "new",
            "--every-chain",
            "--index",
            &expected_index.to_string(),
        ]);
        let accounts = created.as_array().expect("one entry per chain");
        assert_eq!(
            accounts.len(),
            CHAINS.len(),
            "wallet {expected_index} is incomplete"
        );
        for account in accounts {
            assert_eq!(account["index"], expected_index);
        }
        // Every chain, every time.
        let chains: Vec<&str> = accounts
            .iter()
            .map(|a| a["chain"].as_str().unwrap())
            .collect();
        assert_eq!(chains, CHAINS);
    }

    // Three wallets, one account per chain in each, one mnemonic.
    let listed = wallet.json(&["account", "list"]);
    assert_eq!(listed.as_array().unwrap().len(), 3 * CHAINS.len());
    assert_eq!(
        wallet.json(&["recent", "list"]).as_array().unwrap().len(),
        1
    );
}

/// Importing a mnemonic makes the whole wallet, not one chain of it. The bug
/// this pins: an import produced an EVM account and silently left every other
/// chain behind, so the wallet looked like it had lost chains it never had.
#[test]
fn importing_a_mnemonic_can_restore_every_chain_at_once() {
    let wallet = Wallet::new();
    let imported = wallet.json(&[
        "account",
        "import-mnemonic",
        "-m",
        PHRASE,
        "--every-chain",
        "--label",
        "restored",
    ]);
    let accounts = imported.as_array().expect("one entry per chain");
    assert_eq!(accounts.len(), CHAINS.len());
    assert_eq!(
        accounts
            .iter()
            .map(|a| a["chain"].as_str().unwrap())
            .collect::<Vec<_>>(),
        CHAINS
    );
    for account in accounts {
        assert_eq!(account["index"], 0, "one wallet, one index");
    }

    // The addresses are the ones the official SDKs derive, so this restored
    // the wallet rather than making four unrelated ones.
    let vectors = vectors();
    let by_chain = |name: &str| {
        accounts.iter().find(|a| a["chain"] == name).unwrap()["address"]
            .as_str()
            .unwrap()
    };
    assert_eq!(
        by_chain("evm"),
        "0x9858EfFD232B4033E47d90003D41EC34EcaEda94"
    );
    assert_eq!(
        by_chain("solana"),
        vectors["solana"]["accounts"][0]["address"]
            .as_str()
            .unwrap()
    );
    assert_eq!(
        by_chain("cardano"),
        vectors["cardano"]["accounts"][0]["base_addr_testnet"]
            .as_str()
            .unwrap()
    );
}

/// Naming a chain is how you ask for just one, and it still works that way.
#[test]
fn importing_with_a_chain_named_restores_only_that_chain() {
    let wallet = Wallet::new();
    let imported = wallet.json(&[
        "--chain",
        "solana",
        "account",
        "import-mnemonic",
        "-m",
        PHRASE,
        "--label",
        "just-sol",
    ]);
    assert_eq!(imported["chain"], "solana");
    assert_eq!(
        wallet.json(&["account", "list"]).as_array().unwrap().len(),
        1
    );
}

/// A raw private key belongs to one chain and cannot produce the others, so
/// there is deliberately no way to ask it to.
#[test]
fn importing_a_private_key_stays_on_one_chain() {
    let wallet = Wallet::new();
    let imported = wallet.json(&[
        "account",
        "import-key",
        "-k",
        "0x1ab42cc412b618bdea3a599e3c9bae199ebf030895b039e9db1e30dafb12b727",
        "--label",
        "raw",
    ]);
    assert_eq!(imported["chain"], "evm");
    assert_eq!(
        wallet.json(&["account", "list"]).as_array().unwrap().len(),
        1
    );
}

/// Deriving an index makes the wallet at that index — the same thing `New
/// wallet` makes, so the two cannot disagree about what a wallet is.
#[test]
fn deriving_an_index_can_cover_every_chain() {
    let wallet = Wallet::new();
    wallet.json(&[
        "account",
        "import-mnemonic",
        "-m",
        PHRASE,
        "--every-chain",
        "--label",
        "w0",
    ]);

    let derived = wallet.json(&[
        "account",
        "derive",
        "--index",
        "1",
        "--every-chain",
        "--label",
        "w1",
    ]);
    let accounts = derived.as_array().unwrap();
    assert_eq!(accounts.len(), CHAINS.len());
    for account in accounts {
        assert_eq!(account["index"], 1);
    }
    assert_eq!(
        wallet.json(&["account", "list"]).as_array().unwrap().len(),
        2 * CHAINS.len()
    );
}

/// Every chain derives its *own* key at a shared index — the same index is
/// not the same key, which is the whole point of grouping by it.
#[test]
fn one_index_gives_each_chain_a_different_address() {
    let wallet = Wallet::new();
    wallet.json(&[
        "account",
        "import-mnemonic",
        "-m",
        PHRASE,
        "--label",
        "seed",
    ]);
    for chain in ["solana", "cardano", "midnight"] {
        wallet.json(&[
            "--chain",
            chain,
            "account",
            "import-mnemonic",
            "-m",
            PHRASE,
            "--index",
            "0",
            "--label",
            chain,
        ]);
    }
    let listed = wallet.json(&["account", "list"]);
    let at_zero: Vec<&str> = listed
        .as_array()
        .unwrap()
        .iter()
        .filter(|a| a["index"] == 0)
        .map(|a| a["address"].as_str().unwrap())
        .collect();
    assert_eq!(at_zero.len(), 4);
    let distinct: std::collections::BTreeSet<&&str> = at_zero.iter().collect();
    assert_eq!(distinct.len(), 4, "index 0 must not collide across chains");
}

#[test]
fn address_indices_advance_per_chain_rather_than_globally() {
    let wallet = Wallet::new();
    wallet.json(&["account", "new", "--every-chain", "--label", "first"]);

    // A second Solana address continues Solana's sequence, and leaves the
    // other chains' sequences alone.
    let second = wallet.json(&["--chain", "solana", "account", "new", "--label", "sol-1"]);
    assert_eq!(second["index"], 1);
    assert_eq!(second["derivation_path"], "m/44'/501'/1'/0'");

    let cardano = wallet.json(&["--chain", "cardano", "account", "new", "--label", "ada-1"]);
    assert_eq!(cardano["index"], 1, "cardano has its own sequence");
    assert_eq!(cardano["derivation_path"], "m/1852'/1815'/0'/0/1");
}

// ================================================================= signatures

#[test]
fn every_chain_signs_and_verifies_its_own_scheme() {
    let wallet = seeded();
    for chain in CHAINS {
        let signed = wallet.json(&["--chain", chain, "sign", "hello causewaybay"]);
        let signature = signed["signature"].as_str().unwrap();
        assert!(signature.starts_with("0x"), "{chain}");

        let checked = wallet.json(&[
            "--chain",
            chain,
            "verify",
            "--message",
            "hello causewaybay",
            "--signature",
            signature,
        ]);
        assert_eq!(
            checked["valid"], true,
            "{chain} could not verify its own signature"
        );
        assert_eq!(checked["chain"], chain);
        assert!(!checked["scheme"].as_str().unwrap().is_empty());
    }
}

#[test]
fn a_tampered_message_fails_verification_on_every_chain() {
    let wallet = seeded();
    for chain in CHAINS {
        let signature = wallet.json(&["--chain", chain, "sign", "original"])["signature"]
            .as_str()
            .unwrap()
            .to_string();
        let checked = wallet.json(&[
            "--chain",
            chain,
            "verify",
            "--message",
            "tampered",
            "--signature",
            &signature,
        ]);
        assert_eq!(
            checked["valid"], false,
            "{chain} accepted a tampered message"
        );
    }
}

/// Each chain uses a different signature scheme, so one chain's signature must
/// not check out under another's — a signature that verified anywhere would
/// mean the scheme was not actually being applied.
#[test]
fn a_signature_from_one_chain_does_not_verify_on_another() {
    let wallet = seeded();
    let evm_signature = wallet.json(&["--chain", "evm", "sign", "hello"])["signature"]
        .as_str()
        .unwrap()
        .to_string();

    for chain in ["solana", "cardano", "midnight"] {
        let mut checked = wallet.cmd(&[
            "--json",
            "--chain",
            chain,
            "verify",
            "--message",
            "hello",
            "--signature",
            &evm_signature,
        ]);
        let output = checked.output().unwrap();
        let envelope: Value =
            serde_json::from_str(String::from_utf8_lossy(&output.stdout).trim()).unwrap();
        // Either refused as the wrong shape, or checked and found invalid.
        // What must never happen is `valid: true`.
        let verdict = envelope
            .get("data")
            .and_then(|d| d.get("valid"))
            .and_then(Value::as_bool);
        assert_ne!(
            verdict,
            Some(true),
            "{chain} accepted an EVM signature: {envelope}"
        );
    }
}

// ============================================================ chain isolation

#[test]
fn naming_an_account_from_another_chain_is_refused_with_the_way_out() {
    let wallet = seeded();
    let error = wallet
        .cmd(&["--json", "--chain", "solana", "account", "show", "evm"])
        .output()
        .unwrap();
    let envelope: Value =
        serde_json::from_str(String::from_utf8_lossy(&error.stdout).trim()).unwrap();
    assert_eq!(envelope["ok"], false);
    assert_eq!(envelope["error"]["code"], "usage");
    let message = envelope["error"]["message"].as_str().unwrap();
    assert!(message.contains("--chain evm"), "{message}");
}

#[test]
fn erc20_is_refused_off_evm() {
    let wallet = seeded();
    assert_eq!(
        wallet.json_error(&["--chain", "solana", "erc20", "info", "-t", "0xabc"]),
        "usage"
    );
}

#[test]
fn a_private_key_from_the_wrong_chain_is_refused_on_import() {
    let wallet = Wallet::new();
    // A 32-byte EVM key is not a Cardano extended key pair, and Cardano must
    // say so rather than deriving something plausible from the bytes.
    assert_eq!(
        wallet.json_error(&[
            "--chain",
            "cardano",
            "account",
            "import-key",
            "-k",
            "0x1ab42cc412b618bdea3a599e3c9bae199ebf030895b039e9db1e30dafb12b727",
        ]),
        "invalid_private_key"
    );
}

// =================================================================== networks

#[test]
fn a_bare_network_name_shared_by_two_chains_is_refused_rather_than_guessed() {
    let wallet = Wallet::new();
    assert_eq!(
        wallet.json_error(&["-n", "devnet", "info"]),
        "unknown_network"
    );
    // Naming the chain resolves it.
    assert_eq!(
        wallet.json(&["--chain", "solana", "-n", "devnet", "network", "current"])["key"],
        "solana-devnet"
    );
    assert_eq!(
        wallet.json(&["--chain", "midnight", "-n", "devnet", "network", "current"])["key"],
        "midnight-devnet"
    );
}

/// `testnet` and `mainnet` meant Cronos before the wallet had other chains,
/// and every existing config and script says so.
#[test]
fn the_legacy_bare_network_names_still_mean_cronos() {
    let wallet = Wallet::new();
    for (alias, key, id) in [
        ("testnet", "cronos-testnet", 338),
        ("mainnet", "cronos-mainnet", 25),
    ] {
        let current = wallet.json(&["-n", alias, "network", "current"]);
        assert_eq!(current["key"], key);
        assert_eq!(current["chain_id"], id);
    }
}

/// An address that carries its network must be rendered for the network in
/// view, not for the one the store happens to hold.
///
/// Three chains put the network inside the address, so one key is two strings
/// and a record can only keep one of them — the default network's, which is a
/// test network on all three. Showing that string under a mainnet heading
/// offers a deposit address that cannot receive there, and on the chains whose
/// reads go by address it asks the node about somewhere nobody is watching,
/// which comes back as a balance of zero.
///
/// Found by a GUI test: the LÖVE wallet list, pointed at eCash mainnet, was
/// drawing the `ectest:` face.
#[test]
fn an_account_shows_the_address_of_the_network_in_view() {
    let wallet = seeded();
    // `(chain, testnet network, mainnet network, mainnet prefix)`.
    let crossings = [
        ("cardano", "cardano-preprod", "cardano-mainnet", "addr1"),
        ("ecash", "ecash-testnet", "ecash-mainnet", "ecash:"),
    ];

    for (chain, testnet, mainnet, prefix) in crossings {
        let on_testnet = wallet.json(&["--chain", chain, "-n", testnet, "account", "show", chain]);
        let on_mainnet = wallet.json(&["--chain", chain, "-n", mainnet, "account", "show", chain]);

        let testnet_address = on_testnet["address"].as_str().unwrap();
        let mainnet_address = on_mainnet["address"].as_str().unwrap();
        assert_ne!(
            testnet_address, mainnet_address,
            "{chain} served one string for both networks"
        );
        assert!(
            mainnet_address.starts_with(prefix),
            "{chain} on {mainnet}: {mainnet_address}"
        );
        // The account is the same account: only its rendering moved.
        assert_eq!(on_testnet["id"], on_mainnet["id"], "{chain}");
        assert_eq!(on_testnet["label"], on_mainnet["label"], "{chain}");
        assert_eq!(
            on_testnet["private_key"], on_mainnet["private_key"],
            "{chain}"
        );

        // And each rendering is one that chain will accept on that network.
        assert!(
            wallet
                .cmd(&[
                    "--json",
                    "--chain",
                    chain,
                    "-n",
                    mainnet,
                    "balance",
                    "--address",
                    mainnet_address,
                ])
                .output()
                .is_ok(),
            "{chain}"
        );
        assert_eq!(
            wallet.json_error(&[
                "--chain",
                chain,
                "-n",
                mainnet,
                "balance",
                "--address",
                testnet_address,
            ]),
            "invalid_address",
            "{chain}: a testnet address was accepted on {mainnet}"
        );
    }
}

/// The listing is where a person reads an address off to hand it over, so it
/// follows each chain's own network — every row, not only the one in view.
#[test]
fn the_account_listing_renders_every_chain_on_its_own_network() {
    let wallet = seeded();
    wallet.json(&["--chain", "ecash", "network", "use", "ecash-mainnet"]);

    let listed = wallet.json(&["account", "list"]);
    let row = |chain: &str| -> String {
        listed
            .as_array()
            .unwrap()
            .iter()
            .find(|a| a["chain"] == chain)
            .unwrap_or_else(|| panic!("no {chain} row"))["address"]
            .as_str()
            .unwrap()
            .to_string()
    };

    // eCash moved to mainnet, so its row moved with it.
    assert!(row("ecash").starts_with("ecash:"), "{}", row("ecash"));
    // The chains that did not move are unchanged, which is the other half:
    // one chain's network must not re-render another's.
    assert!(
        row("cardano").starts_with("addr_test1"),
        "{}",
        row("cardano")
    );
    assert!(row("evm").starts_with("0x"), "{}", row("evm"));

    // The human rendering says the same thing as the JSON.
    let human =
        String::from_utf8(wallet.cmd(&["account", "list"]).output().unwrap().stdout).unwrap();
    assert!(human.contains(&row("ecash")), "{human}");
}

/// `info` names the *wallet's* active account, which is not always on the
/// chain in view — so its address follows its own chain's network, and the
/// chain in view must not re-render it.
#[test]
fn info_reports_the_active_address_on_its_own_chains_network() {
    let wallet = seeded();

    // While the EVM account is the active one, the address `info` names is
    // its own, whatever chain the command is pointed at.
    let elsewhere = wallet.json(&["--chain", "ecash", "info"]);
    assert_eq!(elsewhere["active_account"], "evm");
    assert_eq!(
        elsewhere["active_address"], "0x9858EfFD232B4033E47d90003D41EC34EcaEda94",
        "the chain in view re-rendered another chain's account"
    );

    // Make the eCash account active, and the address follows eCash's network.
    wallet.json(&["--chain", "ecash", "account", "use", "ecash"]);
    wallet.json(&["--chain", "ecash", "network", "use", "ecash-testnet"]);
    let on_testnet = wallet.json(&["info"]);
    assert!(
        on_testnet["active_address"]
            .as_str()
            .unwrap()
            .starts_with("ectest:"),
        "{on_testnet}"
    );

    wallet.json(&["--chain", "ecash", "network", "use", "ecash-mainnet"]);
    let on_mainnet = wallet.json(&["info"]);
    assert!(
        on_mainnet["active_address"]
            .as_str()
            .unwrap()
            .starts_with("ecash:"),
        "{on_mainnet}"
    );
}

/// An account with a key this wallet cannot re-derive from still lists: the
/// stored string is shown rather than the listing failing.
///
/// Nothing produces such a record today, and the fallback exists so that a
/// record from a future build — or a hand-edited log — degrades to showing
/// what is on file instead of taking `account list` down with it.
#[test]
fn an_account_whose_key_cannot_be_read_still_lists() {
    let wallet = Wallet::new();
    wallet.json(&[
        "--chain",
        "ecash",
        "account",
        "import-mnemonic",
        "-m",
        PHRASE,
        "--label",
        "xec",
    ]);

    let path = wallet.home.path().join("accounts.jsonl");
    let text = std::fs::read_to_string(&path).unwrap();
    let broken: String = text
        .lines()
        .map(|line| {
            let mut record: Value = serde_json::from_str(line).unwrap();
            record["private_key"] = serde_json::json!("0xnot-a-key");
            format!("{record}\n")
        })
        .collect();
    std::fs::write(&path, broken).unwrap();

    let listed = wallet.json(&["account", "list"]);
    let rows = listed.as_array().unwrap();
    assert_eq!(rows.len(), 1);
    // The address on record, unchanged, rather than an error.
    assert!(
        rows[0]["address"].as_str().unwrap().starts_with("ectest:"),
        "{}",
        rows[0]
    );
}

#[test]
fn a_chain_and_a_network_that_disagree_are_refused() {
    let wallet = Wallet::new();
    assert_eq!(
        wallet.json_error(&["--chain", "solana", "-n", "cronos-mainnet", "info"]),
        "unknown_network"
    );
}

#[test]
fn each_chain_remembers_its_own_network() {
    let wallet = seeded();
    wallet.json(&["--chain", "solana", "network", "use", "solana-testnet"]);
    wallet.json(&["--chain", "cardano", "network", "use", "cardano-preview"]);

    assert_eq!(
        wallet.json(&["--chain", "solana", "network", "current"])["key"],
        "solana-testnet"
    );
    assert_eq!(
        wallet.json(&["--chain", "cardano", "network", "current"])["key"],
        "cardano-preview"
    );
    // Switching one chain's network left the other's alone.
    assert_eq!(
        wallet.json(&["--chain", "evm", "network", "current"])["key"],
        "cronos-testnet"
    );
}

#[test]
fn midnight_reads_and_submits_through_different_endpoints() {
    let wallet = Wallet::new();
    let current = wallet.json(&["--chain", "midnight", "network", "current"]);
    let indexer = current["endpoint"].as_str().unwrap();
    let node = current["submit_endpoint"].as_str().unwrap();
    assert!(indexer.contains("indexer."), "{indexer}");
    assert!(node.contains("rpc."), "{node}");
    assert_ne!(indexer, node);
}

// ====================================================================== chains

#[test]
fn the_chains_command_lists_every_chain_and_its_capabilities() {
    let wallet = Wallet::new();
    let listed = wallet.json(&["chains"]);
    let rows = listed.as_array().unwrap();
    assert_eq!(rows.len(), CHAINS.len());

    let names: Vec<&str> = rows.iter().map(|c| c["chain"].as_str().unwrap()).collect();
    assert_eq!(names, CHAINS);

    for row in rows {
        assert!(!row["networks"].as_array().unwrap().is_empty());
        assert!(!row["derivation_path"].as_str().unwrap().is_empty());
    }

    // The capability flags say what each chain can actually do.
    let by_name = |name: &str| rows.iter().find(|c| c["chain"] == name).unwrap().clone();
    assert_eq!(by_name("evm")["capabilities"]["tokens"], true);
    assert_eq!(
        by_name("evm")["capabilities"]["recoverable_signatures"],
        true
    );
    assert_eq!(by_name("solana")["capabilities"]["faucet"], true);
    assert_eq!(by_name("cardano")["capabilities"]["faucet"], false);
    assert_eq!(
        by_name("midnight")["capabilities"]["recoverable_signatures"],
        false
    );
}

// ======================================================================= store

/// The store gained a `chain` column; a wallet written before it must still
/// replay, and its accounts are EVM ones.
#[test]
fn an_account_record_without_a_chain_replays_as_evm() {
    let wallet = Wallet::new();
    wallet.json(&[
        "account",
        "import-mnemonic",
        "-m",
        PHRASE,
        "--label",
        "legacy",
    ]);

    // Rewrite the log the way the pre-multi-chain wallet wrote it.
    let path = wallet.home.path().join("accounts.jsonl");
    let text = std::fs::read_to_string(&path).unwrap();
    let stripped: String = text
        .lines()
        .map(|line| {
            let mut record: Value = serde_json::from_str(line).unwrap();
            record.as_object_mut().unwrap().remove("chain");
            format!("{record}\n")
        })
        .collect();
    std::fs::write(&path, stripped).unwrap();

    let listed = wallet.json(&["account", "list"]);
    assert_eq!(listed.as_array().unwrap().len(), 1);
    assert_eq!(listed[0]["chain"], "evm");
    assert_eq!(
        listed[0]["address"],
        "0x9858EfFD232B4033E47d90003D41EC34EcaEda94"
    );
}

#[test]
fn accounts_carry_their_chain_through_the_store() {
    let wallet = seeded();
    let listed = wallet.json(&["account", "list"]);
    let rows = listed.as_array().unwrap();
    assert_eq!(rows.len(), CHAINS.len());
    for (row, chain) in rows.iter().zip(CHAINS) {
        assert_eq!(row["chain"], chain);
    }

    // And the log itself records it, so the Python CLI reads the same thing.
    let log = wallet.read_log("accounts.jsonl");
    for record in &log {
        assert!(record["chain"].is_string(), "{record}");
    }
}

/// Whichever chain is asked for, a command lands on an account of that chain
/// without the user having to `account use` first.
#[test]
fn each_chain_resolves_its_own_active_account() {
    let wallet = seeded();
    // The overall active account is the first one made, an EVM account.
    assert_eq!(wallet.json(&["info"])["chain"], "evm");

    for chain in CHAINS {
        let shown = wallet.json(&["--chain", chain, "account", "show"]);
        assert_eq!(
            shown["chain"], chain,
            "--chain {chain} picked the wrong account"
        );
    }
}

#[test]
fn info_summarises_every_chain_the_wallet_holds() {
    let wallet = seeded();
    let info = wallet.json(&["info"]);
    assert_eq!(info["accounts"], CHAINS.len());

    let chains = info["chains"].as_array().unwrap();
    assert_eq!(chains.len(), CHAINS.len());
    for row in chains {
        assert_eq!(row["accounts"], 1, "{row}");
        assert!(row["network"].as_str().unwrap().starts_with(
            row["chain"]
                .as_str()
                .unwrap()
                .replace("evm", "cronos")
                .as_str()
        ));
    }
}

// ================================================================== utilities

#[test]
fn export_carries_every_chains_secret_in_its_own_encoding() {
    let wallet = seeded();
    for chain in CHAINS {
        let exported = wallet.json(&["--chain", chain, "account", "export", chain]);
        let secret = exported["private_key"].as_str().unwrap();
        assert!(!secret.is_empty(), "{chain} exported no key");

        // Re-importing the exported key must reproduce the same address, which
        // is the only thing that makes an export worth having.
        let reimported = wallet.json(&[
            "--chain",
            chain,
            "account",
            "import-key",
            "-k",
            secret,
            "--label",
            &format!("{chain}-again"),
        ]);
        assert_eq!(
            reimported["address"], exported["address"],
            "{chain} did not round-trip through its exported key"
        );
    }
}

/// `network use` on another chain's network has to *stay* switched.
///
/// The wallet resolves its chain from the active account when nothing else
/// says otherwise, so switching the network without moving the account left
/// the next command on the chain just left: "Network is now Solana Devnet"
/// followed by a Cronos balance. Announced and undone in one breath.
#[test]
fn switching_to_another_chains_network_moves_the_wallet_with_it() {
    let wallet = Wallet::new();
    wallet.json(&["account", "new", "--every-chain"]);
    assert_eq!(wallet.json(&["network", "current"])["chain"], "evm");

    wallet.json(&["network", "use", "solana-devnet"]);
    assert_eq!(
        wallet.json(&["network", "current"])["key"],
        "solana-devnet",
        "the switch did not stick"
    );
    assert_eq!(wallet.json(&["account", "show"])["chain"], "solana");

    // And back again, to the network that chain was left on rather than to a
    // default: each chain remembers its own.
    wallet.json(&["network", "use", "cronos-mainnet"]);
    wallet.json(&["network", "use", "solana-devnet"]);
    wallet.json(&["network", "use", "cronos-mainnet"]);
    assert_eq!(
        wallet.json(&["network", "current"])["key"],
        "cronos-mainnet"
    );
    assert_eq!(wallet.json(&["account", "show"])["chain"], "evm");
}

/// A wallet with nothing on the chain it moves to still moves — and arrives
/// holding the account it always had there.
///
/// A wallet is one phrase and one index, and every chain derives its own
/// account at that index; a store that has only ever written the EVM one is
/// missing a record, not an account. Before this the move landed nowhere, and
/// every front end covered for it the same wrong way — by going on showing the
/// chain just left. The screen said Solana over a column of `0x…`, which is an
/// address offered for a deposit that cannot arrive on the chain named above
/// it.
#[test]
fn switching_to_a_chain_with_no_account_derives_one_there() {
    let wallet = Wallet::new();
    // EVM only: nothing to make active on Solana.
    wallet.json(&["account", "new"]);
    let switched = wallet.json(&["network", "use", "solana-devnet"]);
    assert_eq!(wallet.json(&["network", "current"])["key"], "solana-devnet");

    let derived = switched["derived"].as_array().expect("a list of addresses");
    assert_eq!(derived.len(), 1, "one wallet, one Solana account");
    let shown = wallet.json(&["account", "show"]);
    assert_eq!(shown["chain"], "solana");
    assert_eq!(shown["address"], derived[0]);

    // The same address the wallet would have had if it had been made on every
    // chain from the start — this derives an account, it does not invent one.
    let phrase = wallet.json(&["account", "show", "--secret", "--chain", "evm"])["mnemonic"]
        .as_str()
        .expect("the phrase is stored")
        .to_string();
    let fresh = Wallet::new();
    let imported = fresh.json(&[
        "--yes",
        "account",
        "import-mnemonic",
        "-m",
        &phrase,
        "--every-chain",
    ]);
    let same = imported
        .as_array()
        .expect("one account per chain")
        .iter()
        .find(|a| a["chain"] == "solana")
        .expect("a solana account");
    assert_eq!(same["address"], derived[0]);

    // And moving again does not write a second copy of what is already there.
    wallet.json(&["network", "use", "cronos-testnet"]);
    let again = wallet.json(&["network", "use", "solana-devnet"]);
    assert_eq!(
        again["derived"].as_array().expect("a list").len(),
        0,
        "the account was already held; nothing was owed"
    );
}

/// A wallet with no phrase to derive from is left exactly as it is.
///
/// An account imported from a bare private key is one key on one chain and
/// nothing else — there is no seed behind it, so it has no face on Solana to
/// write down. Inventing one would attach an address to a wallet whose owner
/// cannot reach it from anything they hold.
#[test]
fn a_private_key_wallet_gains_nothing_on_a_chain_switch() {
    let wallet = Wallet::new();
    wallet.json(&[
        "account",
        "import-key",
        "--private-key",
        "0x4c0883a69102937d6231471b5dbb6204fe5129617082792ae468d01a3f362318",
    ]);
    let switched = wallet.json(&["network", "use", "solana-devnet"]);
    assert_eq!(switched["derived"].as_array().expect("a list").len(), 0);
    assert_eq!(
        wallet.json(&["account", "list"]).as_array().unwrap().len(),
        1,
        "nothing may be added to a wallet that cannot derive it"
    );
}

#[test]
fn amounts_are_parsed_at_each_chains_own_scale() {
    let wallet = seeded();
    // A send that cannot reach a node still parses its amount first, so a
    // fraction finer than the chain allows is refused before anything else.
    for (chain, too_fine) in [
        ("cardano", "0.0000001"),   // 6 decimals
        ("midnight", "0.0000001"),  // 6 decimals
        ("solana", "0.0000000001"), // 9 decimals
    ] {
        let code = wallet.json_error(&[
            "--yes", "--chain", chain, "send", "--to", "unused", "--amount", too_fine,
        ]);
        assert!(
            code == "invalid_amount" || code == "invalid_address",
            "{chain} reported {code} for an over-precise amount"
        );
    }
}
